### PR TITLE
docker-compose version upgraded to 3

### PR DESCRIPTION
**Pull request by RHV044**
Fix for #143 

```docker-compose up```  works as explained in the docs.

### CODE REVIEW

**Comment by rafariossaa** [comment]
Hi,
  I was not able to reproduce the issue.
  Were you typing the file or did you copy and paste it ? If so, maybe some control character was introduced.
  I am using docker version: `20.10.12` on ubuntu 21.10.

**Comment by RHV044** [comment]
Hey,
That's weird.

I downloaded the file using curl.
I have docker engine 'minimum' api version 1.12 and I've read something about a similar issue on older versions of docker. Maybe when using docker-compose 2, it is using an older docker engine api version installed on my system
 
Does that makes sense?

**Comment by rafariossaa** [comment]
I think yes, it could be the API version or also how the client pass the data to the API.

If it helps, these are the versions I have:

```bash
$ docker version

Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:34 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  
  
$ docker-compose version
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
  
```

**Comment by rafariossaa** [comment]
Hi,
  Did you have a chance to check this ?

**Pull request closed without merging**
